# Generated by Django 3.1.7 on 2021-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20210322_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_town',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='exit'),
            preserve_default=False,
        ),
    ]
